default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: booker

development:
  <<: *default
  database: booking_web_development

test:
  <<: *default
  database: booking_web_test

staging:
  <<: *default
  database: booking_web
  password: booker-web
  host: 23.101.67.216
  variables:
    tcp_keepalives_idle: 60
    tcp_keepalives_interval: 60
    tcp_keepalives_count: 100
  
# production:
#   <<: *default
#   database: booking_web_production
#   username: booking_web
#   password: <%= ENV['BOOKING_WEB_DATABASE_PASSWORD'] %>
